version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "orestis-auth"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tdq777qzl8gm"
s3_prefix = "orestis-auth"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AuthenticationDomainPrefix=\"orestis-auth\" BackendAuthenticationScope=\"https://www.example.org/\""
image_repositories = []
